#!/usr/bin/env bash
# Generated by claude-kit. Blocks hand-edits to generated migration files.
# Wired as PreToolUse on Edit only — a brand-new migration still needs Write.
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty')

[ -z "$FILE_PATH" ] && exit 0


if [[ "$FILE_PATH" == *"/Data/Migrations/"* && "$FILE_PATH" == *.cs ]]; then
  echo "EF Core migrations are generated, not written. Change the entity or its IEntityTypeConfiguration and run 'dotnet ef migrations add <Name> --output-dir Data/Migrations' instead." >&2
  exit 2
fi

exit 0
