#!/usr/bin/env bash
# Generated by claude-kit. Restates the project's Key Rules after a compaction,
# since that is exactly when they fall out of context.
set -euo pipefail

cat <<'EOF'
Reminder — React Shadcn key rules:

- Backend and frontend are **separate concerns** — never mix them in a single agent
- No business logic in controllers — controllers delegate to a scoped service
- Request models are validated before the service is reached; services assume valid input
- Soft delete is enforced by a global query filter on the DbContext — never call `Remove(entity)`, set `IsDeleted` instead
- Never hand-edit files under `Data/Migrations/` — change the entity and run `dotnet ef migrations add`
- Endpoints are authenticated by JWT bearer token; the fallback policy denies anonymous access unless an endpoint opts out with `[AllowAnonymous]`
- Authorization is role-based and deny-by-default — a new endpoint is closed unless it explicitly opts out
- Frontend and backend are **separate concerns** — never mix them in a single agent
- This is a client-rendered SPA — there are no Server Components; every component runs in the browser

Verify with: dotnet build
EOF

exit 0
