#!/usr/bin/env bash
# Generated by claude-kit. Restates the project's Key Rules after a compaction,
# since that is exactly when they fall out of context.
#
# The loop-critical lines are the last two. A compact is the single event a
# bounded loop cannot survive on its own: the attempt counter lives in the
# model's context and silently resets to a fresh 3, which is precisely the
# runaway the cap exists to prevent. This is the reminder that it is on disk.
set -euo pipefail

cat <<'EOF'
Reminder — Nextjs MUI key rules:

- Backend and frontend are **separate concerns** — never mix them in a single agent
- No business logic in controllers — controllers delegate to injectable services
- Request DTOs carry class-validator decorators and pass through the global `ValidationPipe`
- Every read excludes soft-deleted rows — compose `eq(table.isDeleted, false)` into the `where`
- CRUD lives in `CrudService<TTable, TId, TCreate, TUpdate, TListRequest, TListItem>` — extend it rather than re-writing paging, filtering or sorting per feature
- Never hand-edit files under `apps/api/drizzle/` — change the schema and run `npx drizzle-kit generate`
- Endpoints are authenticated by JWT bearer token; the fallback policy denies anonymous access unless an endpoint opts out with `[AllowAnonymous]`
- Authorization is role-based and deny-by-default — a new endpoint is closed unless it explicitly opts out
- Frontend and backend are **separate concerns** — never mix them in a single agent
- Components are Server Components unless they need state, effects or browser APIs — add `"use client"` only then

- To verify ANY change run: .claude/scripts/verify.sh <quick|tests|full|integration>
  Never run the underlying build/lint/test commands by hand — only its VERDICT
  block is authoritative, and a FAIL is a stop, not a suggestion
- Never stage or commit docs/plans/** or docs/qa/** — they are
  working artifacts, deliberately not git-ignored
- Never run destructive git (checkout/restore/stash/clean/reset --hard) — the
  tree carries work that exists nowhere else
- The full rule list is .claude/skills/shared/safety-invariants.md
- Mid-loop? Your attempt counters are in docs/plans/<ID>.state.json, not in
  this context — read them back rather than restarting the count:
  .claude/scripts/plan-state.sh <ID> show
EOF

exit 0
