#!/usr/bin/env bash
# Generated by claude-kit. Restates the project's Key Rules after a compaction,
# since that is exactly when they fall out of context.
set -euo pipefail

cat <<'EOF'
Reminder — Backend Only key rules:

- Backend and frontend are **separate concerns** — never mix them in a single agent
- No business logic in controllers — controllers delegate to injectable services
- Request DTOs carry class-validator decorators and pass through the global `ValidationPipe`
- Every read excludes soft-deleted rows — compose `eq(table.isDeleted, false)` into the `where`
- Never hand-edit files under `apps/api/drizzle/` — change the schema and run `npx drizzle-kit generate`

Verify with: npm --workspace apps/api run build
EOF

exit 0
