#!/usr/bin/env bash
# Generated by claude-kit. Blocks edits to files that a generator owns.
# Wired as PreToolUse on Edit|Write — these paths should never be authored by hand.
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty')

[ -z "$FILE_PATH" ] && exit 0


if [[ "$FILE_PATH" == *"/drizzle/meta/"* ]]; then
  echo "This is a generated drizzle-kit snapshot. Change the schema in apps/api/src/db/schema and regenerate — hand-editing it corrupts migration history." >&2
  exit 2
fi

exit 0
