#!/usr/bin/env bash
# Generated by claude-kit. Blocks hand-edits to generated migration files.
# Wired as PreToolUse on Edit only — a brand-new migration still needs Write.
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty')

[ -z "$FILE_PATH" ] && exit 0


if [[ "$FILE_PATH" == *"/drizzle/"* && "$FILE_PATH" == *.sql ]]; then
  echo "Drizzle migrations are generated, not written. Change the schema in apps/api/src/db/schema and run 'npx drizzle-kit generate' from apps/api instead." >&2
  exit 2
fi

exit 0
